SEED_COURSES = [
    {"kla": "English", "course_name": "English Advanced", "stage": "Stage 6", "code": "ENG_ADV"},
    {"kla": "English", "course_name": "English Standard", "stage": "Stage 6", "code": "ENG_STD"},
    {"kla": "Mathematics", "course_name": "Mathematics Advanced", "stage": "Stage 6", "code": "MATH_ADV"},
    {"kla": "Mathematics", "course_name": "Mathematics Extension 1", "stage": "Stage 6", "code": "MATH_X1"},
    {"kla": "Science", "course_name": "Biology", "stage": "Stage 6", "code": "BIO"},
    {"kla": "Science", "course_name": "Chemistry", "stage": "Stage 6", "code": "CHEM"},
    {"kla": "Science", "course_name": "Physics", "stage": "Stage 6", "code": "PHYS"},
    {"kla": "HSIE", "course_name": "Legal Studies", "stage": "Stage 6", "code": "LEGAL"},
    {"kla": "HSIE", "course_name": "Economics", "stage": "Stage 6", "code": "ECON"},
    {"kla": "HSIE", "course_name": "Geography", "stage": "Stage 6", "code": "GEOG"},
    {"kla": "HSIE", "course_name": "Modern History", "stage": "Stage 6", "code": "MOD_HIST"},
    {"kla": "HSIE", "course_name": "Society & Culture", "stage": "Stage 6", "code": "SOC_CULT"},
]

COURSE_OUTCOMES = {
    "ENG_ADV": [
        {"code": "EN12-1", "description": "Demonstrates understanding of how texts are shaped by context"},
        {"code": "EN12-2", "description": "Analyzes language features and text structures"},
        {"code": "EN12-3", "description": "Composes complex texts for different purposes and audiences"},
        {"code": "EN12-4", "description": "Evaluates the ways texts represent ideas and values"},
        {"code": "EN12-5", "description": "Critically analyses and evaluates perspectives in texts"},
        {"code": "EN12-6", "description": "Reflects on personal responses to texts"},
        {"code": "EN12-7", "description": "Demonstrates control of language for effect"},
        {"code": "EN12-8", "description": "Researches and uses sources appropriately"},
    ],
    "ENG_STD": [
        {"code": "EN11-1", "description": "Demonstrates understanding of texts and their contexts"},
        {"code": "EN11-2", "description": "Analyzes language features and text structures"},
        {"code": "EN11-3", "description": "Composes texts for different purposes"},
        {"code": "EN11-4", "description": "Reflects on personal responses to texts"},
        {"code": "EN11-5", "description": "Researches and uses sources effectively"},
    ],
    "MATH_ADV": [
        {"code": "MA12-1", "description": "Uses algebraic techniques to solve problems"},
        {"code": "MA12-2", "description": "Applies calculus to solve problems"},
        {"code": "MA12-3", "description": "Uses statistical analysis to draw conclusions"},
        {"code": "MA12-4", "description": "Models financial situations using mathematics"},
        {"code": "MA12-5", "description": "Communicates mathematical reasoning clearly"},
    ],
    "MATH_X1": [
        {"code": "MX1-1", "description": "Applies advanced calculus techniques"},
        {"code": "MX1-2", "description": "Uses combinatorial and polynomial methods"},
        {"code": "MX1-3", "description": "Models complex mathematical situations"},
        {"code": "MX1-4", "description": "Proves mathematical propositions"},
    ],
    "BIO": [
        {"code": "BIO12-1", "description": "Explains the structure and function of cells and organelles"},
        {"code": "BIO12-2", "description": "Analyzes the mechanisms of heredity and gene expression"},
        {"code": "BIO12-3", "description": "Evaluates the impact of biotechnology on society"},
        {"code": "BIO12-4", "description": "Investigates ecosystem dynamics and biodiversity"},
        {"code": "BIO12-5", "description": "Demonstrates safe and ethical laboratory practices"},
    ],
    "CHEM": [
        {"code": "CHEM12-1", "description": "Explains properties of matter using atomic theory"},
        {"code": "CHEM12-2", "description": "Analyzes chemical reactions and stoichiometry"},
        {"code": "CHEM12-3", "description": "Evaluates the role of chemistry in industry"},
        {"code": "CHEM12-4", "description": "Investigates acid-base and redox reactions"},
        {"code": "CHEM12-5", "description": "Demonstrates safe laboratory techniques"},
    ],
    "PHYS": [
        {"code": "PHYS12-1", "description": "Explains kinematics and dynamics concepts"},
        {"code": "PHYS12-2", "description": "Analyzes wave and electromagnetic phenomena"},
        {"code": "PHYS12-3", "description": "Investigates quantum and nuclear physics"},
        {"code": "PHYS12-4", "description": "Applies electricity and magnetism principles"},
        {"code": "PHYS12-5", "description": "Conducts scientific investigations effectively"},
    ],
    "LEGAL": [
        {"code": "LEG12-1", "description": "Explains the nature and sources of law"},
        {"code": "LEG12-2", "description": "Analyzes the criminal justice system"},
        {"code": "LEG12-3", "description": "Evaluates human rights protections"},
        {"code": "LEG12-4", "description": "Investigates the operation of Australian courts"},
        {"code": "LEG12-5", "description": "Communicates legal arguments effectively"},
    ],
    "ECON": [
        {"code": "ECO12-1", "description": "Explains economic models and policy objectives"},
        {"code": "ECO12-2", "description": "Analyzes the operation of financial markets"},
        {"code": "ECO12-3", "description": "Evaluates government economic policies"},
        {"code": "ECO12-4", "description": "Investigates international trade and globalization"},
        {"code": "ECO12-5", "description": "Interprets economic data and trends"},
    ],
    "GEOG": [
        {"code": "GEO12-1", "description": "Explains geographical patterns and processes"},
        {"code": "GEO12-2", "description": "Analyzes human-environment interactions"},
        {"code": "GEO12-3", "description": "Evaluates sustainability strategies"},
        {"code": "GEO12-4", "description": "Applies geographical tools and technologies"},
        {"code": "GEO12-5", "description": "Conducts geographical investigations"},
    ],
    "MOD_HIST": [
        {"code": "MH12-1", "description": "Explains historical causes and effects"},
        {"code": "MH12-2", "description": "Analyzes historical perspectives and interpretations"},
        {"code": "MH12-3", "description": "Evaluates historical sources and evidence"},
        {"code": "MH12-4", "description": "Communicates historical arguments effectively"},
        {"code": "MH12-5", "description": "Demonstrates understanding of historiographical concepts"},
    ],
    "SOC_CULT": [
        {"code": "SC12-1", "description": "Explains social and cultural concepts"},
        {"code": "SC12-2", "description": "Analyzes the processes of socialization"},
        {"code": "SC12-3", "description": "Evaluates cross-cultural perspectives"},
        {"code": "SC12-4", "description": "Applies social research methods"},
        {"code": "SC12-5", "description": "Communicates social science arguments effectively"},
    ],
}
